apiVersion: v1
kind: Service
metadata:
  name: simple-webapp-flask-service
spec:
  selector:
    app: simple-webapp-flask 
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  
  