apiVersion: v1
kind: Service
metadata:
  name: simple-webapp-flask-service
spec:
  selector:
    app: simple-webapp-flask 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    # nodePort: 43275
  type: NodePort
  selcetor:
    app: simple-webapp-flask